FROM node:24.13.0-alpine3.23 AS builder

WORKDIR /data/website/app

ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN npm install -g pnpm

COPY . ./

RUN pnpm install --filter @projectname/api \
  && pnpm install --filter @projectname/shared \
  && pnpm prisma:push \
  && pnpm build:api

CMD node api/dist/src/main.js

