FROM node:24.13.0-alpine3.23

WORKDIR /data/website/xxx

ENV PNPM_HOME=/root/.local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN npm install -g pnpm

COPY . ./

RUN pnpm install \
  && npx prisma@4.15.0 generate --schema=api/prisma/schema.prisma \
  && pnpm build:api

CMD pnpm prisma:push && node dist/api/index.js

